# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
sudo: required
cache: packages
r_github_packages:
  - cran/survival
  - dkahle/ggmap
apt_packages:
  - libnetcdf-dev
  - udunits-bin
  - libudunits2-dev
  - netcdf-bin
  - libproj-dev
  - libcurl4-gnutls-dev
  - libdap-dev
  - libgdal-dev
  - libgdal1h
  - libhdf5-7 = 1.8.11-3ubuntu1~precise1~ppa1
  - libhdf5-dev
  - libhdf5-serial-dev
  - libgdal-dev
  - libgdal1-dev
